- name: hostname
  tags: [hostname]
  block:
  - assert:
      that:
      - hostname is defined
  
  - name: set hostname in /etc/conf.d/hostname
    lineinfile:
      dest: /etc/conf.d/hostname
      regexp: '^hostname='
      line: 'hostname="{{ hostname }}"'
      state: present
    notify: restart hostname
