- name: dnsmasq
  tags: [dnsmasq]
  block:
  - name: validate network.dns.upstream variable
    assert:
      that:
      - network.dns.upstream in ['connman', 'google', 'opendns', 'cloudflare']
  
  - name: dnsmasq.conf
    notify: restart dnsmasq
    template:
      src: etc_dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: 0644
  
  - name: autostart dnsmasq on boot
    service:
      name: dnsmasq
      runlevel: default
      enabled: true
