- name: check if /bin/zsh exists
  register: stat_bin_zsh
  stat:
    path: /bin/zsh

- name: set user's shell to /bin/zsh
  when: stat_bin_zsh.stat.exists
  user:
    name: '{{ user }}'
    shell: /bin/zsh

- name: .zshrc deployment
  copy:
    src: DOTzshrc
    dest: '{{ user_home_dir }}/.zshrc'
    owner: '{{ user }}'
    group: '{{ user_group_id }}'
    mode: 0600
